=== manami-project/anime-offline-database/dead-entries/dead-entries.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/manami-project/anime-offline-database/blob/raw/dead-entries/dead-entries.schema.json",
    "title": "anime-offline-database",
    "description": "Updated every week: A JSON based anime dataset containing the most important meta data as well as cross references to various anime sites such as MAL, ANIDB, ANILIST, KITSU and more...",
    "type": "object",
    "required": [
        "license",
        "repository",
        "lastUpdate",
        "deadEntries"
    ],
    "properties": {
        "license": {
            "description": "Information about the license of the dataset.",
            "type": "object",
            "required": [
                "name",
                "url"
            ],
            "properties": {
                "name": {
                    "description": "Name of the license.",
                    "const": "GNU Affero General Public License v3.0"
                },
                "url": {
                    "description": "URL to the whole license file.",
                    "const": "https://github.com/manami-project/anime-offline-database/blob/master/LICENSE"
                }
            }
        },
        "repository": {
            "description": "URL of this github repository which is the source of the dataset.",
            "const": "https://github.com/manami-project/anime-offline-database"
        },
        "lastUpdate": {
            "description": "The date on which the file was updated in the format: YYYY-MM-DD.",
            "type": "string"
        },
        "deadEntries": {
            "description": "IDs of anime which have been removed from the respective meta data provider.",
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        }
    }
}

=== manami-project/anime-offline-database/dead-entries/anidb.json
{
  "license": {
    "name": "GNU Affero General Public License v3.0",
    "url": "https://github.com/manami-project/anime-offline-database/blob/master/LICENSE"
  },
  "repository": "https://github.com/manami-project/anime-offline-database",
  "lastUpdate": "2024-09-16",
  "deadEntries": [
    "10002",
    "10003",
    "10004",
    "10013",
    "10014",
    "10017",
    "10018",
    "10019",
    "10026",
    "10028",
    "10029",
    "10030",
    "10032",
    "10033",
    "10034",
    "10036",
    "10039",
    "10042",
    "10043",
    "10044",
    "10045",
    "10047",
    "10056",
    "10061",
    "10062",
    "10063",
    "10068",
    "10070",
    "10072",
    "10078",
    "10079",
    "10083",
    "10088",
    "10089",
    "10092",
    "10099",
    "10100",
    "10106",
    "10108",
    "1011",
    "10112",
    "1012",
    "1013",
    "1014",
    "10142",
    "10156",
    "10157",
    "10158",
    "10160",
    "10163",
    "10164",
    "10165",
    "1017",
    "10175",
    "10176",
    "10183",
    "10184",
    "10185",
    "10189",
    "1019",
    "10192",
    "10194",
    "10195",
    "10196",
    "10204",
    "1021",
    "10213",
    "10214",
    "10216",
    "10219",
    "10221",
    "10224",
    "10229",
    "10230",
    "10231",
    "10233",
    "10236",
    "10237",
    "10239",
    "10256",
    "10258",
    "10259",
    "1026",
    "10260",
    "10261",
    "10263",
    "10264",
    "10265",
    "10266",
    "10267",
    "10268",
    "10270",
    "10275",
    "10277",
    "10280",
    "10285",
    "10287",
    "10296",
    "10297",
    "10299",
    "1030",
    "10300",
    "10301",
    "10302",
    "10303",
    "10304",
    "10307",
    "10309",
    "10312",
    "10316",
    "10324",
    "10327",
    "10328",
    "10331",
    "10332",
    "10334",
    "10335",
    "10336",
    "10337",
    "10338",
    "10339",
    "1034",
    "10340",
    "10341",
    "10342",
    "10343",
    "10344",
    "10345",
    "10346",
    "10347",
    "10355",
    "10358",
    "10362",
    "10363",
    "10364",
    "10371",
    "10375",
    "10377",
    "10380",
    "10381",
    "10387",
    "10388",
    "10393",
    "10408",
    "10410",
    "10412",
    "10413",
    "10416",
    "10418",
    "1042",
    "10420",
    "10425",
    "10429",
    "10433",
    "10435",
    "10437",
    "10448",
    "10449",
    "10451",
    "10455",
    "10459",
    "10460",
    "10461",
    "10463",
    "10464",
    "10465",
    "10466",
    "10467",
    "10468",
    "10469",
    "1047",
    "10470",
    "10471",
    "10472",
    "10473",
    "10474",
    "10479",
    "1048",
    "10481",
    "10484",
    "10485",
    "10487",
    "10488",
    "10489",
    "1049",
    "10490",
    "10491",
    "10492",
    "10493",
    "10494",
    "10495",
    "10497",
    "10502",
    "10503",
    "10504",
    "10507",
    "10508",
    "1051",
    "10510",
    "10511",
    "10512",
    "10516",
    "10520",
    "10521",
    "10524",
    "10533",
    "10534",
    "10543",
    "10544",
    "10545",
    "10547",
    "10552",
    "10557",
    "10558",
    "10559",
    "10560",
    "10561",
    "10582",
    "10594",
    "10595",
    "10604",
    "10606",
    "10608",
    "10612",
    "10615",
    "10616",
    "1062",
    "10625",
    "10629",
    "10630",
    "10637",
    "10642",
    "10650",
    "10652",
    "10653",
    "10654",
    "10655",
    "10658",
    "10659",
    "1066",
    "10660",
    "10664",
    "10668",
    "1067",
    "10670",
    "10671",
    "10675",
    "10677",
    "10678",
    "10679",
    "10682",
    "10686",
    "10694",
    "10695",
    "10696",
    "10699",
    "10701",
    "10703",
    "10704",
    "10705",
    "10706",
    "10711",
    "10716",
    "10718",
    "10723",
    "10724",
    "10738",
    "10740",
    "10752",
    "10753",
    "10754",
    "10756",
    "10757",
    "10772",
    "10775",
    "10777",
    "10786",
    "10788",
    "10789",
    "10790",
    "10791",
    "10792",
    "10793",
    "10794",
    "10797",
    "10801",
    "10802",
    "10805",
    "10806",
    "10807",
    "10817",
    "10819",
    "1082",
    "10821",
    "10822",
    "10826",
    "10827",
    "10828",
    "10834",
    "10837",
    "10838",
    "10839",
    "10840",
    "10844",
    "10845",
    "10850",
    "10851",
    "10852",
    "10856",
    "10868",
    "10870",
    "10871",
    "10872",
    "10876",
    "1088",
    "10883",
    "10884",
    "1089",
    "10893",
    "10895",
    "10900",
    "10906",
    "10911",
    "10915",
    "10920",
    "10921",
    "10922",
    "10923",
    "10924",
    "10926",
    "10933",
    "10940",
    "10942",
    "10943",
    "10945",
    "1095",
    "1096",
    "10964",
    "1097",
    "10973",
    "10975",
    "10979",
    "1098",
    "10983",
    "10996",
    "11001",
    "11003",
    "11004",
    "11005",
    "11010",
    "11012",
    "11013",
    "11014",
    "11017",
    "1102",
    "11021",
    "11022",
    "11030",
    "11033",
    "11034",
    "11035",
    "11038",
    "11042",
    "11043",
    "11044",
    "11045",
    "11046",
    "11047",
    "11051",
    "11052",
    "11057",
    "11061",
    "11062",
    "11065",
    "11069",
    "11070",
    "11078",
    "11079",
    "1108",
    "11083",
    "11085",
    "11087",
    "1110",
    "11106",
    "11107",
    "11108",
    "11109",
    "11111",
    "11113",
    "11116",
    "11117",
    "11118",
    "11120",
    "11127",
    "11128",
    "1113",
    "1114",
    "11141",
    "1115",
    "11159",
    "1116",
    "11160",
    "11162",
    "1117",
    "11175",
    "11179",
    "11182",
    "11188",
    "11189",
    "11190",
    "11191",
    "11192",
    "11193",
    "11194",
    "11196",
    "1120",
    "11202",
    "11206",
    "11208",
    "1121",
    "11212",
    "11215",
    "11222",
    "11224",
    "11227",
    "1123",
    "11236",
    "1124",
    "11242",
    "11245",
    "11254",
    "11256",
    "11258",
    "11269",
    "1127",
    "11271",
    "1128",
    "11280",
    "11290",
    "1130",
    "11308",
    "1131",
    "11316",
    "11324",
    "11325",
    "11327",
    "11328",
    "1133",
    "11334",
    "11339",
    "1134",
    "11340",
    "11346",
    "11351",
    "1136",
    "11368",
    "11381",
    "11388",
    "11401",
    "11402",
    "11414",
    "11416",
    "11425",
    "11426",
    "11437",
    "1145",
    "11454",
    "11455",
    "11460",
    "11461",
    "1147",
    "11471",
    "11474",
    "11475",
    "11476",
    "11477",
    "11479",
    "11482",
    "11494",
    "11496",
    "11497",
    "11501",
    "11510",
    "11511",
    "11517",
    "1152",
    "11522",
    "11525",
    "11528",
    "11539",
    "11548",
    "1157",
    "11574",
    "11581",
    "11582",
    "11583",
    "11584",
    "11586",
    "1159",
    "1160",
    "11603",
    "11604",
    "11609",
    "11610",
    "11611",
    "1162",
    "11621",
    "11635",
    "1164",
    "11640",
    "11641",
    "11642",
    "11644",
    "11657",
    "1166",
    "11666",
    "11675",
    "1168",
    "11685",
    "11686",
    "11687",
    "1169",
    "11693",
    "11695",
    "11697",
    "11698",
    "11714",
    "11718",
    "11719",
    "11722",
    "11732",
    "11738",
    "11749",
    "1175",
    "11755",
    "11759",
    "11769",
    "11770",
    "11771",
    "11773",
    "11774",
    "11779",
    "1178",
    "11787",
    "11802",
    "11807",
    "1181",
    "11811",
    "11812",
    "11813",
    "11817",
    "11818",
    "11821",
    "11824",
    "1183",
    "11830",
    "11832",
    "1184",
    "11845",
    "11847",
    "11853",
    "11856",
    "11858",
    "1186",
    "11866",
    "11867",
    "11872",
    "11873",
    "11876",
    "1188",
    "11882",
    "11885",
    "11892",
    "11898",
    "119",
    "11906",
    "11912",
    "11923",
    "11932",
    "11933",
    "11944",
    "11947",
    "11954",
    "11956",
    "11962",
    "11963",
    "11967",
    "1197",
    "11973",
    "11975",
    "11976",
    "1198",
    "1199",
    "11990",
    "11999",
    "1200",
    "12000",
    "12001",
    "12005",
    "1201",
    "12011",
    "12013",
    "12015",
    "12017",
    "1202",
    "12026",
    "12028",
    "1203",
    "1204",
    "1205",
    "12052",
    "12056",
    "12066",
    "1207",
    "12071",
    "12072",
    "12076",
    "12086",
    "12096",
    "12097",
    "12099",
    "1211",
    "1212",
    "12120",
    "12126",
    "12133",
    "12134",
    "12139",
    "12144",
    "12145",
    "1215",
    "12154",
    "12157",
    "12159",
    "12160",
    "12161",
    "12162",
    "12163",
    "12164",
    "12165",
    "12166",
    "12167",
    "12168",
    "12169",
    "12170",
    "12171",
    "12172",
    "12173",
    "12174",
    "12175",
    "12176",
    "12177",
    "12178",
    "12179",
    "12180",
    "12181",
    "12182",
    "12183",
    "12184",
    "12185",
    "12186",
    "12187",
    "12188",
    "12189",
    "12190",
    "12208",
    "12213",
    "12219",
    "12229",
    "12236",
    "12239",
    "12242",
    "12243",
    "12259",
    "1226",
    "12260",
    "12267",
    "12272",
    "1228",
    "12281",
    "12285",
    "12286",
    "12293",
    "12294",
    "12295",
    "12299",
    "1230",
    "12302",
    "12303",
    "12304",
    "12305",
    "12306",
    "1231",
    "12312",
    "12313",
    "12325",
    "12334",
    "12335",
    "12340",
    "12341",
    "12342",
    "12343",
    "12345",
    "12354",
    "12355",
    "12357",
    "12365",
    "12368",
    "12370",
    "12375",
    "12376",
    "12377",
    "12378",
    "12379",
    "12383",
    "12386",
    "1239",
    "12391",
    "12396",
    "12397",
    "12401",
    "12404",
    "12405",
    "12412",
    "12421",
    "12427",
    "12437",
    "1244",
    "12440",
    "12444",
    "12445",
    "12446",
    "12448",
    "1245",
    "12463",
    "12464",
    "12466",
    "12475",
    "12476",
    "12477",
    "1248",
    "12486",
    "12489",
    "12490",
    "12497",
    "12499",
    "12511",
    "12512",
    "12513",
    "12520",
    "12528",
    "12547",
    "12552",
